from .login_screen import LoginScreen
from .register_screen import RegisterScreen
from .main_interface_screen import MainInterfaceScreen
from .account_details_screen import AccountDetailsScreen
from .add_recipe_screen import AddRecipeScreen
from .ai_gen_screen import AIGenScreen
from .favourites_screen import FavouritesScreen
from .home_screen import HomeScreen
from .recipe_details_screen import RecipeDetailsScreen